algo = input('Digite algo: ')
print(('O tipo primitivo desse valor é {}'.format(type(algo))))
print('É alfanumerico? {}'.format(algo.isalnum()))
print('É alfabetico? {}'.format(algo.isalpha()))
print('É ASCII? {}'.format(algo.isascii()))
print('É digito? {}'.format(algo.isdigit()))
print('É minusculo? {}'.format(algo.islower()))
print('É decimal ? {}'.format(algo.isdecimal()))
print('É identificavel ? {}'.format(algo.isidentifier()))
print('É númerico ? {}'.format(algo.isnumeric()))
print('É imprimível ? {}'.format(algo.isprintable()))
print('É espaço ? {}'.format(algo.isspace()))
print('É título ? {}'.format(algo.istitle()))
print('É maiúsculo ? {}'.format(algo.isupper()))
# Concluido